services:
  tests:
    build: .
    image: docker-module
    depends_on:
      - chrome

  chrome:
    image: selenium/node-chrome:4.34.0-20250727
    platform: linux/amd64
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  firefox:
    image: selenium/node-firefox:nightly
    platform: linux/amd64
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub

  selenium-hub:
    image: selenium/hub:4.34.0-20250727
    container_name: selenium-hub

    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
